### ISSUE TITLE
Complete data not received sometimes in run and compile APIs

### ISSUE THREAD

**Issue by mithunkumarnallu** [scriptnull/he-sdk-nodejs#1]
When using the compile API, I realized that sometimes I get the error "Can't set headers after they are sent". Later understood that I am not getting the whole data in my callbacks when using these APIs.
Http module returns data in chunks and its difficult to understand when the whole data is received when I am using these APIs.

**Comment by scriptnull** [comment]
Thank you for pointing out. I was in a hurry while writing the stuff , so I missed out this detail. However , I have made patch release now which should return the full result instead of chunks. 

You can find the implementation details from this commit. https://github.com/scriptnull/he-sdk-nodejs/commit/7df6ed93763f27227757c7c228669f1e5f8aa1dd

Try npm install he-sdk-nodejs to download v0.0.3 and evaluate with your test cases and kindly notify me.

**Comment by mithunkumarnallu** [comment]
Looks good! Thanks for the quick turn-around.
